// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Models;

namespace WebApi.Migrations
{
    [DbContext(typeof(WarehouseContext))]
    partial class WarehouseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Models.Inventory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MonetaryValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("TotalRentDuration")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Inventories");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Inventory");
                });

            modelBuilder.Entity("WebApi.Models.BicycleRack", b =>
                {
                    b.HasBaseType("WebApi.Models.Inventory");

                    b.Property<int>("Assertion")
                        .HasColumnType("int");

                    b.Property<int>("BikeLimit")
                        .HasColumnType("int");

                    b.Property<double>("LiftPower")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("BicycleRack");
                });

            modelBuilder.Entity("WebApi.Models.RoofRack", b =>
                {
                    b.HasBaseType("WebApi.Models.Inventory");

                    b.Property<string>("AppearenceDescription")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("IsLockable")
                        .HasColumnType("bit");

                    b.Property<double>("LiftPower")
                        .HasColumnName("RoofRack_LiftPower")
                        .HasColumnType("float");

                    b.Property<int>("Opening")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("RoofRack");
                });

            modelBuilder.Entity("WebApi.Models.WheelChain", b =>
                {
                    b.HasBaseType("WebApi.Models.Inventory");

                    b.Property<double>("ChainThickness")
                        .HasColumnType("float");

                    b.Property<string>("TireDimensions")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("WheelChain");
                });
#pragma warning restore 612, 618
        }
    }
}
